### PR TITLE
Use string view in error log

### PR DESCRIPTION
**Pull request by Brett208**

### CODE REVIEW

**Comment by Brett208** [comment]
I wonder why the makefile update worked for circleci and not for travis-ci? It looks like the Macintosh build for travis-ci worked.

**Comment by DanRStevens** [comment]
We're still using Travis? What a ... travesty? :wink:

I think I know what the problem is though. TravisCI had a way of using really ancient builds, and never really updating things:
```
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
```

That would be why C++17 features don't work. The compiler is from 2015.

We should switch to using CircleCI for those builds.

**Comment by DanRStevens** [comment]
Adding a reference to issue #17, which is currently blocking this work.

**Comment by Brett208** [comment]
It does not appear to be building clang with circleci yet

**Review by DanRStevens — APPROVED** [review]
Yeah, I only just pushed the change to enable the Clang build (#45). The earlier stuff just pushed a new Docker image with Clang installed, and updated some of the support code (#44). I hadn't yet setup a build that used it until now.

**Comment by Brett208** [comment]
Ah, thanks.

**Pull request merged**
